include:
  - project: nse/ci
    file:
      - /ci/lib/tox-bb5.yml
      - /ci/jobs/build-package.yml
      - /ci/jobs/build-wheels.yml
      - /ci/jobs/publish-package.yml
      - /ci/jobs/docs.yml
      - /ci/jobs/publish-docs.yml
  - project: hpc/gitlab-pipelines
    file: spack-build-components.gitlab-ci.yml

workflow:
  rules:
    # Rules taken from official docs to avoid duplicated pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'


test-cpp-unit:
  stage: test
  tags:
    - bb5_map
  before_script:
    - !reference [.bb5, clean-env]
  script:
    - source ${SPACK_ROOT}/share/spack/setup-env.sh;
    - spack load boost@1.70
    - module load unstable cmake gcc
    - cmake -S . -B build
    - cmake --build build -j2
    - cd build && ctest -E Python


setup_spack:
  stage: .pre
  extends: .spack_setup


test-bare-ubuntu:
  stage: test
  tags: [kubernetes]
  image: bbpgitlab.epfl.ch:5050/hpc/spatialindex/ubuntu_20.04_devel
  variables:
    KUBERNETES_MEMORY_LIMIT: 5Gi    # memory overrides
    KUBERNETES_MEMORY_REQUEST: 4Gi  # memory overrides
    PIP_PACKAGES: pytest h5py
  before_script:
    - !reference [.define-functions]
    - ln -s /usr/bin/python3 /usr/bin/python
    - !reference [.setup-venv]
  script:
    - apt install -y libboost-filesystem1.71-dev libboost-serialization1.71-dev libboost-test1.71-dev
    - pip install -v -e .
    - pytest


test-spack:
  stage: test
  tags:
    - bb5_map
  variables:
    PIP_PACKAGES: "pytest h5py"
  before_script:
    - !reference [.bb5, clean-env]
    - !reference [.define-functions]
  script:
    - source $SPACK_ROOT/share/spack/setup-env.sh
    - spack dev-build spatial-index@develop
    - !reference [.bb5, load-python-39]
    - !reference [.setup-venv]
    - spack load spatial-index@develop
    - mv spatial_index _dont_interfere
    - pytest


test-bb5-py39:
  extends: .tox-template
  variables:
    TOXENV: flake8, py39  # boost depends on py38
    PRE_BUILD_COMMAND: |
      source ${SPACK_ROOT}/share/spack/setup-env.sh;
      spack load boost@1.70

# The following stages are overrides. Dont rename
# Always add the manual option to create sdist/wheel or upload
build-package:
  tags: []
  rules:
    - when: always

build-wheels:
  tags: [kubernetes]
  image: bbpgitlab.epfl.ch:5050/hpc/spatialindex/manylinux2014_boost_x86_64
  variables:
    KUBERNETES_MEMORY_LIMIT: 5Gi    # memory overrides
    KUBERNETES_MEMORY_REQUEST: 4Gi  # memory overrides
    SYS_PACKAGES: boost169-devel
    PRE_BUILD_COMMAND: free;
      export BOOST_INCLUDEDIR="/usr/include/boost169";
      export BOOST_LIBRARYDIR="/usr/lib64/boost169"
    TEST_RUN_TOX: "false"  # MVDtool doesnt have wheels
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'
    - if: $CI_COMMIT_TAG
    - when: manual
      allow_failure: true

publish-package:
  tags: []
  rules:
    - if: $CI_COMMIT_TAG
    - when: manual
      allow_failure: true

docs:
  variables:
    TOXENV: docs
    PRE_BUILD_COMMAND: |
      source ${SPACK_ROOT}/share/spack/setup-env.sh;
      spack load boost@1.70
  artifacts:
    paths:
      - "${PYTHON_PROJECT_DIR-.}/docs/_build/"

publish-docs:
  tags: []
  variables:
    SYS_PACKAGES: openssh-clients
    PIP_PACKAGES: docs_internal_upload
  script:
    - docs-internal-upload --docs-path docs/_build
  rules:
    - if: $CI_COMMIT_TAG
    - when: manual
      allow_failure: true
